---
 environment: production
 chdir: /var/www/bb
 address: 127.0.0.1
 user: root
 group: root
 port: 4567
 pid: /var/www/bb/pids/thin.pid
 rackup: /var/www/bb/config.ru
 log: /var/www/bb/logs/thin.log
 max_conns: 1024
 timeout: 30
 max_persistent_conns: 512
 daemonize: true

